name = "halalend/poc"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'halalend/poc'"

[repository]
user = "halalend"
project = "poc"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
